from django.conf.urls import url
from sales import views

urlpatterns = [
    url(r'^sales_summary/$', views.SalesSummaryView.as_view(), name='sales_summary'),
    url(r'^ajax_sales_summary/$', views.ajax_summarys, name='ajax_sales_summary'),
    url(r'^sales_summary_detail/(?P<pk>[0-9]+)/$', views.SalesDetailView.as_view(), name='sales_summary_detail'),
    url(r'^ajax_filter_sales_summary/$', views.ajax_summarys_filter, name='ajax_filter_sales_summary'),
    url(r'^ajax_delete_sales_summary/$', views.summarydelete, name='ajax_delete_sales_summary'),
    url(r'^ajax_update_sales_summary/$', views.UpdateSummary, name='ajax_update_sales_summary'),
    url(r'^ajax_add_sales_do/$', views.doadd, name='ajax_add_sales_do'),
    url(r'^ajax_sales_do_item_add/$', views.doItemAdd, name='ajax_sales_do_item_add'),
    url(r'^ajax_add_sales_do_doc/$', views.dodocadd, name='ajax_add_sales_do_doc'),
    url(r'^ajax_delete_sales_do/$', views.deleteDo, name='ajax_delete_sales_do'),
    url(r'^sales-detail/(?P<pk>[0-9]+)/delivery-order-detail/(?P<dopk>[0-9]+)/$', views.DoDetailView.as_view(), name='sales_do_detail'),
    url(r'^ajax_update_sales_delivery_order/$', views.UpdateDeliveryOrder, name='ajax_update_sales_delivery_order'),
    url(r'^export_sales_do_pdf/(?P<value>\w+)/$', views.exportDoPDF, name='export_sales_do_pdf'),
    url(r'^ajax_get_sales_do_item/$', views.getDoItem, name='ajax_get_sales_do_item'),
    url(r'^ajax_delete_sales_delivery_item/$', views.deleteDOItem, name='ajax_delete_sales_delivery_item'),
    url(r'^ajax_add_sales_delivery_sign/$', views.deliverysignadd, name='ajax_add_sales_delivery_sign'),
    url(r'^ajax_get_sales_delivery_sign/$', views.getDeliverySign, name='ajax_get_sales_delivery_sign'),

    url(r'^company/$', views.CompanyList.as_view(), name='all_company'),
    url(r'^ajax_add_company/$', views.companyadd, name='ajax_add_company'),
    url(r'^ajax_add_contact_company/$', views.contactCompanyAdd, name='ajax_add_contact_company'),
    url(r'^ajax_get_company/$', views.getCompany, name='ajax_get_company'),
    url(r'^ajax_delete_company/$', views.companydelete, name='ajax_delete_company'),
    url(r'^ajax_all_company/$', views.ajax_companys, name='ajax_all_company'),
    url(r'^ajax_filter_company/$', views.ajax_companys_filter, name='ajax_filter_company'),
    url(r'^ajax-export-company/$', views.ajax_export_company, name='ajax-export-company'),
    url(r'^ajax-import-company/$', views.ajax_import_company, name='ajax-import-company'),

    #contact part
    url(r'^contact/$', views.ContactList.as_view(), name='all_contact'),
    url(r'^ajax_add_contact/$', views.contactadd, name='ajax_add_contact'),
    url(r'^ajax_get_contact/$', views.getContact, name='ajax_get_contact'),
    url(r'^ajax_all_contact/$', views.ajax_contacts, name='ajax_all_contact'),
    url(r'^ajax_filter_contact/$', views.ajax_contacts_filter, name='ajax_filter_contact'),
    url(r'^ajax_delete_contact/$', views.contactdelete, name='ajax_delete_contact'),
    url(r'^ajax-export-contact/$', views.ajax_export_contact, name='ajax-export-contact'),
    url(r'^ajax-import-contact/$', views.ajax_import_contact, name='ajax-import-contact'),

    #quotation part
    url(r'^quotation/$', views.QuotationList.as_view(), name='all_quotation'),
    url(r'^ajax_qtt_items/$', views.ajax_qtt_items, name='ajax_qtt_items'),
    url(r'^ajax_check_scopes/$', views.ajax_check_scopes, name='ajax_check_scopes'),
    url(r'^ajax_add_quotation/$', views.quotationadd, name='ajax_add_quotation'),
    url(r'^ajax_get_quotation/$', views.getQuotation, name='ajax_get_quotation'),
    url(r'^ajax_delete_quotation/$', views.quotationdelete, name='ajax_delete_quotation'),
    url(r'^ajax_read_notify/$', views.readnotify, name='ajax_read_notify'),
    url(r'^ajax_unread_notify/$', views.unreadnotify, name='ajax_unread_notify'),
    url(r'^ajax_remove_notify/$', views.removenotify, name='ajax_remove_notify'),
    url(r'^ajax_all_read_notify/$', views.markUserNotificationsRead, name='ajax_all_read_notify'),
    url(r'^quotation-detail/(?P<pk>[0-9]+)/$', views.QuotationDetailView.as_view(), name='quotation_detail'),
    url(r'^ajax_update_quotation/$', views.UpdateQuotation, name='ajax_update_quotation'),
    url(r'^ajax_update_quotation_override/$', views.UpdateQuotationOverride, name='ajax_update_quotation_override'),
    url(r'^ajax_check_quotation/$', views.check_quotation_number, name='ajax_check_quotation'),
    url(r'^ajax_check_quotation_company/$', views.check_quotation_company, name='ajax_check_quotation_company'),
    url(r'^ajax_get_contact_person/$', views.ajax_get_contact_person, name='ajax_get_contact_person'),
    url(r'^ajax_check_quotation_contactperson/$', views.check_quotation_contact, name='ajax_check_quotation_contactperson'),
    url(r'^ajax_all_quotation/$', views.ajax_quotations, name='ajax_all_quotation'),
    url(r'^ajax_filter_quotation/$', views.ajax_quotations_filter, name='ajax_filter_quotation'),
    url(r'^export_quotation_pdf/(?P<value>\w+)/$', views.exportQuotationPDF, name='export_quotation_pdf'),
    url(r'^export_quotation_excel/(?P<value>\w+)/$', views.exportExcelQuotation, name='export_quotation_excel'),
    url(r'^ajax_add_scope_detail/$', views.scopeadd, name='ajax_add_scope_detail'),
    url(r'^ajax_get_scope/$', views.getScope, name='ajax_get_scope'),
    url(r'^ajax_get_file/$', views.getFile, name='ajax_get_file'),
    url(r'^ajax_delete_scope/$', views.scopedelete, name='ajax_delete_scope'),
    url(r'^ajax_delete_qfile/$', views.qfiledelete, name='ajax_delete_qfile'),
    url(r'^ajax_save_signature/$', views.signaturesave, name='ajax_save_signature'),
    url(r'^ajax_add_qfile/$', views.qfileadd, name='ajax_add_qfile'),
    url(r'^ajax_filter_person/$', views.ajax_filter_person, name='ajax_filter_person'),
    url(r'^ajax_add_subject/$', views.ajax_add_subject, name='ajax_add_subject'),
    url(r'^ajax_add_optional/$', views.ajax_add_optional, name='ajax_add_optional'),
    url(r'^ajax_add_discount/$', views.ajax_add_discount, name='ajax_add_discount'),
    url(r'^ajax_get_subjects/$', views.ajax_get_subjects, name='ajax_get_subjects'),
    url(r'^ajax_get_scope_by_description/$', views.ajax_get_scopedata, name='ajax_get_scope_by_description'),
    url(r'^ajax_subject_items/$', views.ajax_subject_items, name='ajax_subject_items'),
    url(r'^ajax_get_subject/$', views.ajax_get_subject, name='ajax_get_subject'),
    url(r'^ajax_delete_subject/$', views.subjectdelete, name='ajax_delete_subject'),

    #Report part
    url(r'^report/$', views.ReportView.as_view(), name='all_reports'),
    url(r'^sales-item-list/$', views.SalesItemListView.as_view(), name='sales_item_list'),
    url(r'^sales-task-list/$', views.SalesTaskListView.as_view(), name='sales_task_list'),
    url(r'^ajax-add-report/$', views.salereportadd, name='ajax_add_report'),
    url(r'^ajax_get_report_summary/$', views.getReport, name='ajax_get_report_summary'),
    url(r'^ajax_delete_report$', views.reportdelete, name='ajax_delete_report'),
    url(r'^report-detail/(?P<pk>[0-9]+)/$', views.ReportDetailView.as_view(), name='report_detail'),
    url(r'^ajax_update_report/$', views.UpdateReport, name='ajax_update_report'),
    url(r'^ajax_comment/$', views.addSaleComment, name='ajax_comment'),
    url(r'^ajax_get_comment/$', views.getComReport, name='ajax_get_comment'),
    url(r'^ajax_all_report/$', views.ajax_reports, name='ajax_all_report'),
    url(r'^ajax_all_scopes/$', views.ajax_all_scopes, name='ajax_all_scopes'),
    url(r'^ajax_all_tasks/$', views.ajax_all_tasks, name='ajax_all_tasks'),
    url(r'^ajax_filter_report/$', views.ajax_filter_report, name='ajax_filter_report'),
    url(r'^ajax_filter_scope/$', views.ajax_filter_scope, name='ajax_filter_scope'),
    url(r'^ajax_filter_task/$', views.ajax_filter_task, name='ajax_filter_task'),
    url(r'^ajax_delete_comment/$', views.reportcommentdelete, name='ajax_delete_comment'),
]
