version: '3.8'

services:
  web:
    build: ./CNI-ERP
    command: gunicorn -c gunicorn.conf.py erpSolution.wsgi:application
    expose:
      - 8000
    env_file:
      - CNI-ERP/.env
    environment:
      - DJANGO_SETTINGS_MODULE=erpSolution.local
    volumes:
      - static_volume:/home/old-erp/web/staticfiles
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/old-erp/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  static_volume: