# Generated by Django 3.2.16 on 2024-07-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='ref_quot',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
