# Generated by Django 3.2.16 on 2024-07-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_quotation_ref_quot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsubject',
            name='is_optional',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentsubject',
            name='revision_sub_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
